CREATE TABLE IF NOT EXISTS `script_generate_batch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `product_id` BIGINT NOT NULL COMMENT '产品id',
  `user_id` BIGINT NULL COMMENT '用户id',
  `prompt_id` BIGINT NULL COMMENT '提示词id',
  `ad_number` INT NOT NULL DEFAULT 1 COMMENT '请求生成条数',
  `source_type` VARCHAR(32) NOT NULL COMMENT '来源类型：GENERATE/RERUN/FEEDBACK_RERUN',
  `success_count` INT NOT NULL DEFAULT 0 COMMENT '成功条数',
  `fail_count` INT NOT NULL DEFAULT 0 COMMENT '失败条数',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0.处理中 1.完成 2.部分失败 3.失败',
  `request_snapshot` LONGTEXT NULL COMMENT '请求快照',
  `del` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0.否 1.是',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_batch_product_user_time` (`product_id`, `user_id`, `create_time`),
  KEY `idx_batch_prompt` (`prompt_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='脚本生成批次';

CREATE TABLE IF NOT EXISTS `script_generate_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `batch_id` BIGINT NOT NULL COMMENT '批次id',
  `item_seq` INT NOT NULL DEFAULT 1 COMMENT '批次序号',
  `product_id` BIGINT NOT NULL COMMENT '产品id',
  `user_id` BIGINT NULL COMMENT '用户id',
  `prompt_id` BIGINT NULL COMMENT '提示词id',
  `prompt_snapshot` LONGTEXT NULL COMMENT '提示词快照',
  `rule_snapshot` LONGTEXT NULL COMMENT '规则快照',
  `input_snapshot` LONGTEXT NULL COMMENT '输入快照',
  `tag_snapshot` LONGTEXT NULL COMMENT '标签快照',
  `user_input_snapshot` LONGTEXT NULL COMMENT '用户输入快照',
  `case_snapshot` LONGTEXT NULL COMMENT '案例快照',
  `model_name` VARCHAR(64) NULL COMMENT '模型名称',
  `route_strategy` VARCHAR(64) NULL COMMENT '路由策略',
  `output_content` LONGTEXT NULL COMMENT '生成内容',
  `source_type` VARCHAR(32) NOT NULL COMMENT '来源类型：GENERATE/RERUN/FEEDBACK_RERUN',
  `parent_asset_id` BIGINT NULL COMMENT '父资产id',
  `revision_seq` INT NULL COMMENT '修订序号',
  `save_status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已保存：0.否 1.是',
  `saved_asset_id` BIGINT NULL COMMENT '已保存资产id',
  `error_msg` VARCHAR(512) NULL COMMENT '错误信息',
  `del` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0.否 1.是',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_history_batch` (`batch_id`, `item_seq`),
  KEY `idx_history_product_user_time` (`product_id`, `user_id`, `create_time`),
  KEY `idx_history_save_status` (`save_status`, `create_time`),
  KEY `idx_history_saved_asset` (`saved_asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='脚本生成历史';
